apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cfg-composition
spec:
  compositeTypeRef:
    apiVersion: cfg.example.org/v1alpha1
    kind: XCfgResource
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: ConfigMap
                    metadata:
                      namespace: default
            patches:
              - fromFieldPath: spec.data
                toFieldPath: spec.forProvider.manifest.data.sample-key
                type: FromCompositeFieldPath
            name: resource-0
    - step: detect-readiness
      functionRef:
        name: crossplane-contrib-function-auto-ready
